# UUID Store
#!md| [TOML file](https://toml.io/en/)

[stores]
python = '..'

[families]
cute = "67486250-5dbf-11ed-85a7-d0817aaf398c"

[projects.cute]
core = "c7856c22-5d4b-11ed-989b-d0817aaf398c"

[files.py]
fuuid = "627398e0-5d4b-11ed-8755-d0817aaf398c"


# !md| # Table

[database] # - create an example
server = "192.168.1.1"
ports = [8001, 8001, 8002]
connection_max = 5000
enabled = true
entry = 1979-05-27T07:32:00Z
